### PR TITLE
Remove Argo wildcards

### PR DESCRIPTION
**Pull request by jandryuk**
This is part of work to reduce the number of wilcard argo rings
https://github.com/OpenXT/linux-xen-argo/pull/3
https://github.com/OpenXT/xenclient-oe/pull/1238

Starts with the deletion of icavm_t since it's unused AFAIK.  Better to remove it than update it untested.

This replaces a bunch of the argo policies to just eliminate the use of argo wildcards rings.  It relies on other patches to ensure that single source rings are used more often.

A generic argo_comms interfaces is introduced to allow two domains to talk to each other over single source rings.  After specifying that, and with the other PRs, only dom0 and ndvm need wildcard rings.

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [$6702](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6702)

**Review by eric-ch — APPROVED** [review]
LGTM. `argo_comms` makes more sense and is easier to read and use.

**Comment by dozylynx** [comment]
Agree wtih @eric-ch :+1:  `argo_comms` is clearly defined and much easier to read and use - these policy files are definitely better with this. Thanks, @jandryuk .

**Review by jean-edouard — APPROVED** [review]
Merging soon.

**Pull request merged**
