### PR TITLE
x86_64: flask policy for 64-bit support

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1476

### CODE REVIEW

**Comment by jandryuk** [comment]
I prefer https://github.com/OpenXT/xsm-policy/pull/23 to the "Allow stubdoms to map hvm guest resources" commit which should do the same thing.

Since allow `dom0_t ndvm_t:domain2 { setclaim };` is repeated, should it just be put into `policy/modules/xen/xen.if:xen_domain_type`?

**Comment by crogers1** [comment]
Ok so if @jean-edouard merges https://github.com/OpenXT/xsm-policy/pull/23 and I drop the hvm resources commit in this PR, and move the setclaim to xen_domain_type (yea it should definitely go here) this should be good to go?

**Comment by jandryuk** [comment]
Yes, that sounds good.

**Comment by crogers1** [comment]
Updated

**Review by jandryuk — APPROVED** [review]
LGTM

**Pull request merged**
