### PR TITLE
[OXT-118] Added interfaces to allow irq permissions for device_t types. Also gave ...

### PR DESCRIPTION
**Pull request by brendank310**
...stubdom access to those interfaces. This is to resolve denials that result from QEmu 1.4 changes to passthrough within the stubdomain.

### CODE REVIEW

**Comment by jean-edouard** [comment]
LGTM

**Comment by cjp256** [comment]
Cleaned up commit to meet guidelines.

**Comment by flihp** [comment]
This looks like the patch discussed here: https://github.com/brendank310/meta-qemu-1.4-oxt/pull/30

Since you said you intended to roll this back I wasn't expecting to see this go into the main repos. You also point out something that the device_t type is actually an unlabeled type. Do you have more data on this? It's not really my strong suit. The policy language I know but I don't know much about the intricacies of device labeling internal to xen. I'm sure there are labeling rules for devices in there somewhere so we may need to have data w/r to the devices you're testing with to see if / why they're not being labeled properly.

**Comment by brendank310** [comment]
After discussing the changes with @cjp256, I believe this approach is acceptable. I think a more fine-grained labelling policy would be a great idea, perhaps within the https://openxt.atlassian.net/browse/OXT-31 epic. However I think taking this fine-grain labelling approach before a toolstack update could be painful.

**Comment by jean-edouard** [comment]
what about remove_irq?

**Pull request merged**
